# Generated by Django 5.1.7 on 2025-03-28 08:29

import config.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TagCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "memes_count",
                    models.PositiveIntegerField(
                        default=0, help_text="태그가 적용된 밈 수"
                    ),
                ),
                (
                    "bookmarkings_count",
                    models.PositiveIntegerField(
                        default=0, help_text="태그가 적용된 밈들의 총 북마크 수"
                    ),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_counter",
                        to="tag.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag_counter",
                "verbose_name_plural": "tag_counters",
                "db_table": "tag_counters",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="TagUserCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bookmarks_count", models.PositiveIntegerField(default=0)),
                ("bookmarkings_count", models.PositiveIntegerField(default=0)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tag_counters",
                        to="tag.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tag_user_counter",
                "verbose_name_plural": "tag_user_counters",
                "db_table": "tag_user_counters",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tag"), name="unique_tag_user_counter"
                    )
                ],
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
