# Generated by Django 5.2.7 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name='CompanyIndustry',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('name', models.CharField(max_length=100, unique=True)),
      ],
      options={
        'verbose_name': 'Company Industry',
        'verbose_name_plural': 'Company Industries',
        'db_table': 'company_industries',
        'ordering': ['name'],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='CompanySector',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('name', models.CharField(max_length=100, unique=True)),
      ],
      options={
        'verbose_name': 'Company Sector',
        'verbose_name_plural': 'Company Sectors',
        'db_table': 'company_sectors',
        'ordering': ['name'],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='Country',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('code', models.CharField(max_length=10, unique=True, verbose_name='국가 코드')),
        ('name', models.CharField(max_length=100, verbose_name='국가명')),
      ],
      options={
        'verbose_name': 'Country',
        'verbose_name_plural': 'Countries',
        'db_table': 'countries',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='Company',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('name', models.CharField(max_length=255, verbose_name='회사명')),
        ('english_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='영문 회사명')),
        (
          'corp_code',
          models.CharField(
            help_text='DART API에서 사용하는 고유 법인 코드', max_length=20, unique=True, verbose_name='법인 코드 (DART)'
          )
        ),
        ('is_fixed_sector', models.BooleanField(default=False, verbose_name='섹터 고정 여부')),
        ('is_fixed_industry', models.BooleanField(default=False, verbose_name='산업군 고정 여부')),
        ('is_financial', models.BooleanField(default=False, verbose_name='금융업 여부')),
        ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='웹사이트')),
        ('description', models.TextField(blank=True, default='', verbose_name='회사 설명')),
        (
          'industry',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='companies',
            to='companies.companyindustry',
            verbose_name='산업'
          )
        ),
        (
          'sector',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='companies',
            to='companies.companysector',
            verbose_name='섹터'
          )
        ),
        (
          'country',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='companies',
            to='companies.country',
            verbose_name='국가'
          )
        ),
      ],
      options={
        'verbose_name': 'Company',
        'verbose_name_plural': 'Companies',
        'db_table': 'companies',
        'indexes': [models.Index(fields=['name'], name='idx_company_name')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
