# Generated by Django 5.2.7 on 2025-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('companies', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='company',
      name='primary_stock_code',
      field=models.CharField(
        blank=True, help_text='DART 기준 데이터 수집용 / 실제 API에 사용 X', max_length=20, null=True, verbose_name='기본 주식 코드'
      ),
    ),
  ]
