"""
Django settings for palette_api project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
import sentry_sdk
from celery.schedules import crontab

from .logging import DJANGO_GUID, LOGGING  # noqa: F401

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()

# Sentry 설정
SENTRY_DSN = env.str("SENTRY_DSN", default="")
SENTRY_ENVIRONMENT = env.str("SENTRY_ENVIRONMENT", default="development")
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=0.1)

if SENTRY_DSN:
  sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment=SENTRY_ENVIRONMENT,
    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    send_default_pii=True,
    enable_tracing=True,
  )

# import_export 설정
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_TMP_STORAGE_CLASS = "common.storage.CustomTempFolderStorage"
IMPORT_EXPORT_SKIP_ADMIN_LOG = False
IMPORT_EXPORT_CHUNK_SIZE = 100

SECRET_KEY = env.str("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

# Application definition

ADMIN_APPS = [
  "unfold",
  "unfold.contrib.filters",
  "unfold.contrib.forms",
  "unfold.contrib.inlines",
  "unfold.contrib.import_export",
  "admin_object_actions",
]

DJANGO_APPS = [
  "corsheaders",
  "django.contrib.admin",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
]

PACKAGE_APPS = [
  # Django Postgres
  "django.contrib.postgres",
  "psqlextra",
  # Django Extensions
  "django_extensions",
  # NPlusOne
  "nplusone.ext.django",
  # REST Framework
  "rest_framework",
  "rest_framework.authtoken",
  "rest_framework_simplejwt",
  "rest_framework_simplejwt.token_blacklist",
  # Swagger Docs
  "drf_spectacular",
  # Django Filters
  "django_filters",
  # Logging
  "django_guid",
  # Django ADMIN Import Export
  "import_export",
  # Auth
  "allauth",
  "allauth.account",
  "dj_rest_auth",
  "dj_rest_auth.registration",
  "allauth.socialaccount",
  "allauth.socialaccount.providers.kakao",
  # Celery
  "django_celery_beat",
  "django_celery_results",
]

CUSTOM_APPS = [
  "common",
  "api",
  "users",
  "profiles",
  "file_managers",
  "matchmakings",
  "saju",
  "payments",
  "action_trackings",
]

INSTALLED_APPS = ADMIN_APPS + DJANGO_APPS + PACKAGE_APPS + CUSTOM_APPS

MIDDLEWARE = [
  "allow_cidr.middleware.AllowCIDRMiddleware",
  "corsheaders.middleware.CorsMiddleware",
  "django_guid.middleware.guid_middleware",
  "crum.CurrentRequestUserMiddleware",
  "nplusone.ext.django.NPlusOneMiddleware",
  "allauth.account.middleware.AccountMiddleware",
  "django.middleware.security.SecurityMiddleware",
  "django.contrib.sessions.middleware.SessionMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "django.contrib.auth.middleware.AuthenticationMiddleware",
  "django.contrib.messages.middleware.MessageMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
  "config.middlewares.CamelCaseMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [
      BASE_DIR / "templates",
    ],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
      ],
    },
  },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

POSTGRES_DB = env.str("POSTGRES_DB", default="")
POSTGRES_USER = env.str("POSTGRES_USER", default="")
POSTGRES_PASSWORD = env.str("POSTGRES_PASSWORD", default="")
POSTGRES_HOST = env.str("POSTGRES_HOST", default="postgres")
POSTGRES_PORT = env.int("POSTGRES_PORT", default=5432)

TEST_POSTGRES_DB = env.str("TEST_POSTGRES_DB", default="") or POSTGRES_DB
TEST_POSTGRES_USER = env.str("TEST_POSTGRES_USER", default="") or POSTGRES_USER
TEST_POSTGRES_PASSWORD = env.str("TEST_POSTGRES_PASSWORD", default="") or POSTGRES_PASSWORD
TEST_POSTGRES_HOST = env.str("TEST_POSTGRES_HOST", default="") or POSTGRES_HOST
TEST_POSTGRES_PORT = env.int("TEST_POSTGRES_PORT", default=0) or POSTGRES_PORT

DATABASES = {
  "default": {
    "ENGINE": "psqlextra.backend",
    "NAME": POSTGRES_DB,
    "USER": POSTGRES_USER,
    "PASSWORD": POSTGRES_PASSWORD,
    "HOST": POSTGRES_HOST,
    "PORT": POSTGRES_PORT,
    "TEST": {
      "NAME": TEST_POSTGRES_DB,
      "USER": TEST_POSTGRES_USER,
      "PASSWORD": TEST_POSTGRES_PASSWORD,
      "HOST": TEST_POSTGRES_HOST,
      "PORT": TEST_POSTGRES_PORT,
    },
  },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
  BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

AUTH_USER_MODEL = "users.User"

# Swagger Settings

SPECTACULAR_SETTINGS = {
  "TITLE":
  "Palette API",
  "DESCRIPTION":
  "API for Palette Web / Mobile Application",
  "VERSION":
  "1.0.0",
  "SERVE_INCLUDE_SCHEMA":
  False,
  "SWAGGER_UI_OAUTH2_REDIRECT_URL":
  "/docs/oauth2-redirect/",
  "CONTACT": {
    "name": "shinkeonkim",
    "email": "dev.shinkeonkim@gmail.com",
  },
  "CAMELIZE_NAMES":
  True,
  "POSTPROCESSING_HOOKS": [
    "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields",
    "drf_spectacular.hooks.postprocess_schema_enums",
  ],
}

# REST Framework Settings

REST_FRAMEWORK = {
  "DEFAULT_SCHEMA_CLASS":
  "drf_spectacular.openapi.AutoSchema",
  "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated", ),
  "DEFAULT_RENDERER_CLASSES": (
    "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
    "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    "rest_framework.renderers.JSONRenderer",
  ),
  "DEFAULT_PARSER_CLASSES": (
    "djangorestframework_camel_case.parser.CamelCaseFormParser",
    "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
    "djangorestframework_camel_case.parser.CamelCaseJSONParser",
  ),
  "DEFAULT_AUTHENTICATION_CLASSES": (
    "rest_framework.authentication.SessionAuthentication",
    "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
  ),
  "EXCEPTION_HANDLER":
  "common.exceptions.exception_handler.custom_exception_handler",
  "JSON_UNDERSCOREIZE": {
    "no_underscore_before_number": True,
  },
  "DEFAULT_FILTER_BACKENDS": (
    "django_filters.rest_framework.DjangoFilterBackend",
    "rest_framework.filters.OrderingFilter",
    "rest_framework.filters.SearchFilter",
  ),
  "DEFAULT_PAGINATION_CLASS":
  "rest_framework.pagination.PageNumberPagination",
  "PAGE_SIZE":
  10,
  "DATETIME_FORMAT":
  "%s",
  "DATETIME_INPUT_FORMATS": ["%s"],
}

# REST Auth Settings

REST_AUTH = {
  "USE_JWT": True,
  "JWT_AUTH_HTTPONLY": False,
  "JWT_SERIALIZER": "api.v1.users.serializers.JWTSerializer",
}

REST_USE_JWT = True

ACCOUNT_LOGIN_METHODS = {"email"}  # 이메일로 로그인할 수 있다.
ACCOUNT_EMAIL_VERIFICATION = "none"  # 이메일 인증 없이 로그인할 수 있다.
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"

KAKAO_REST_API_KEY = env.str("KAKAO_CLIENT_ID", default="")
KAKAO_ADMIN_KEY = env.str("KAKAO_ADMIN_KEY", default="")
KAKAO_SECRET_KEY = env.str("KAKAO_SECRET_KEY", default="")

SOCIALACCOUNT_PROVIDERS = {
  "kakao": {
    "APP": {
      "client_id": KAKAO_REST_API_KEY,
      "secret": KAKAO_SECRET_KEY,
    },
    "SCOPE": [
      "profile_nickname",
      "profile_image",
      "account_email",
    ],
  }
}

SIMPLE_JWT = {
  "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
  "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
  "ROTATE_REFRESH_TOKENS": True,
  "BLACKLIST_AFTER_ROTATION": True,
  "UPDATE_LAST_LOGIN": False,
  "ALGORITHM": "HS256",
  "SIGNING_KEY": SECRET_KEY,
}

# Slack Bot Settings

SLACK_BOT_TOKEN = env("SLACK_BOT_TOKEN", default="").rstrip()
SLACK_CHANNEL_ID = env("SLACK_CHANNEL_ID", default="").rstrip()

# Django Unfold Settings

UNFOLD = {
  "SITE_TITLE": "Palette Admin",
  "SITE_HEADER": "Palette Admin",
  "SITE_TITLE": "Palette Admin",
  "SITE_BRANDING": "Palette Admin",
  "DASHBOARD_CALLBACK": "users.admin.dashboard_widgets.dashboard_callback",
  "SHOW_HISTORY": True,
  "SHOW_VIEW_ON_SITE": True,
  "SHOW_BACK_BUTTON": False,
}

# ========== Celery settings ==========

REDIS_HOST = env.str("REDIS_HOST", default="palette-redis")
REDIS_PORT = env.str("REDIS_PORT", default="6379")
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", default="django-db")
CELERY_RESULT_EXTENDED = True
CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat 설정
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Celery Beat 스케줄 (한국 시간 기준)

CELERY_BEAT_SCHEDULE = {
  "auto-expire-matching-task": {
    "task": "matchmakings.tasks.auto_expire_matching_task.auto_expire_matching_task",
    "schedule": crontab(hour=4, minute=0),  # 매일 새벽 4시 (KST)
  },
  "cleanup-import-tmp-files": {
    "task": "common.tasks.cleanup_import_tmp_task.cleanup_import_tmp_files",
    "schedule": crontab(hour=3, minute=0),  # 매일 새벽 3시 (KST)
  },
}

# ========== END Celery settings ==========

# ========== Matchmaking settings ==========
# 매칭 생성에 필요한 티켓 수량
MATCHING_TICKET_COST = 50

# 매칭 만료 및 환불 관련 설정
MATCHING_AUTO_REJECT_DAYS = 7  # 호감을 보낸 후 자동 거절까지의 기간 (일)
MATCHING_REFUND_TICKET_AMOUNT = 50  # 만료시 환불할 티켓 수량 / 일단 보낸 티켓 수량과 동일하게 설정

MATCHING_ALGORITHM_NAMES = [
  "RandomAlgorithm",
  "AAlgorithm",
  "BAlgorithm",
  "CAlgorithm",
]

# 추천 횟수 제한 설정
REFERRAL_QUOTA_MAX = 3  # 사용자가 받을 수 있는 최대 추천 횟수
REFERRAL_QUOTA_RECOVERY_HOURS = 4  # 추천 횟수 복구 시간 (시간)
REFERRAL_QUOTA_RESET_TICKET_COST = 30  # 추천 횟수 초기화에 필요한 티켓 수량
# ========== END Matchmaking settings ==========

# ========== Cache settings ==========
# Redis 캐시 설정 (NICE API 세션 등에 사용)
CACHES = {
  "default": {
    "BACKEND": "django.core.cache.backends.redis.RedisCache",
    "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
    "KEY_PREFIX": "palette",
    "TIMEOUT": 900,  # 15분 (본인인증 세션 TTL)
  }
}
# ========== END Cache settings ==========

# ========== NICE API settings ==========
# NICE API 본인인증 관련 설정
NICE_CLIENT_ID = env.str("NICE_CLIENT_ID", default="")
NICE_CLIENT_SECRET = env.str("NICE_CLIENT_SECRET", default="")
NICE_ACCESS_TOKEN = env.str("NICE_ACCESS_TOKEN", default="")
NICE_PRODUCT_ID = env.str("NICE_PRODUCT_ID", default="2101979031")
NICE_RETURN_URL = env.str("NICE_RETURN_URL", default="")

# NICE API URL 설정
NICE_TOKEN_URL = "https://svc.niceapi.co.kr:22001/digital/niceid/oauth/oauth/token"
NICE_CRYPTO_URL = "https://svc.niceapi.co.kr:22001/digital/niceid/api/v1.0/common/crypto/token"
NICE_CHECKPLUS_URL = "https://nice.checkplus.co.kr/cert/request"
# ========== END NICE API settings ==========

# ========== Toss Payments settings ==========
# 토스페이먼츠 API 키
TOSS_PAYMENTS_CLIENT_KEY = env.str("TOSS_PAYMENTS_CLIENT_KEY", default="")
TOSS_PAYMENTS_SECRET_KEY = env.str("TOSS_PAYMENTS_SECRET_KEY", default="")

# 토스페이먼츠 API URL
TOSS_PAYMENTS_API_URL = "https://api.tosspayments.com/v1"

# 결제 성공/실패 리다이렉트 URL
TOSS_PAYMENTS_SUCCESS_URL = env.str(
  "TOSS_PAYMENTS_SUCCESS_URL",
  default="http://localhost:3000/payment/success",
)
TOSS_PAYMENTS_FAIL_URL = env.str(
  "TOSS_PAYMENTS_FAIL_URL",
  default="http://localhost:3000/payment/fail",
)

# ========== END Toss Payments settings ==========

KRW_PRICE_PER_TICKET = 110

# ========== LLM Service settings ==========
DEFAULT_LLM_PROVIDER = env.str("DEFAULT_LLM_PROVIDER", default="openai")
OPENAI_API_KEY = env.str("OPENAI_API_KEY", default="")
ANTHROPIC_API_KEY = env.str("ANTHROPIC_API_KEY", default="")
# ========== END LLM Service settings ==========

# ========== Email settings ==========
# Gmail SMTP 설정
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
# ========== END Email settings ==========

# Proxy 설정 - 실제 클라이언트 IP를 가져오기 위한 설정
# Traefik → Nginx → Django 구조에서 실제 클라이언트 IP를 올바르게 파싱
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Traefik과 Nginx를 신뢰할 수 있는 프록시로 설정
# 192.168.0.0/16: 클러스터 내부 네트워크
TRUSTED_PROXY_HEADERS = [
  "X-Forwarded-For",
  "X-Forwarded-Proto",
  "X-Real-IP",
]
