# Generated by Django 5.1.5 on 2025-03-16 07:46

import config.models.base_model
import django.db.models.deletion
import meme.models.meme
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bookmarking_users_count",
                    models.PositiveIntegerField(
                        default=0, help_text="북마크한 유저 수"
                    ),
                ),
                (
                    "bookmarkings_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="북마크 수 (북마크한 유저 수와 다를 수 있음, 한 유저가 중복 북마크 가능)",
                    ),
                ),
            ],
            options={
                "verbose_name": "meme_counter",
                "verbose_name_plural": "meme_counters",
                "db_table": "meme_counters",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Text", "Text"),
                            ("Image", "Image"),
                            ("Video", "Video"),
                            ("Audio", "Audio"),
                        ],
                        max_length=10,
                        verbose_name="meme type",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="meme title")),
                ("description", models.TextField(verbose_name="meme description")),
                (
                    "original_link",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="original link",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meme",
                        to="file_manager.audio",
                        verbose_name="audio",
                    ),
                ),
            ],
            options={
                "verbose_name": "meme",
                "verbose_name_plural": "memes",
                "db_table": "memes",
            },
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
    ]
