# Generated by Django 5.1.5 on 2025-03-16 07:46

import django.db.models.deletion
import meme.models.meme
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_manager", "0001_initial"),
        ("meme", "0001_initial"),
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_memes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AddField(
            model_name="meme",
            name="tags",
            field=models.ManyToManyField(
                related_name="meme", through="tag.MemeTagging", to="tag.tag"
            ),
        ),
        migrations.AddField(
            model_name="meme",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meme",
                to="file_manager.thumbnail",
                verbose_name="thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="meme",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meme",
                to="file_manager.video",
                verbose_name="video",
            ),
        ),
        migrations.CreateModel(
            name="AudioMeme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("meme.meme",),
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="ImageMeme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("meme.meme",),
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="TextMeme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("meme.meme",),
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="VideoMeme",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("meme.meme",),
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
        migrations.AddField(
            model_name="memecounter",
            name="meme",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="meme.meme"
            ),
        ),
        migrations.AddIndex(
            model_name="meme",
            index=models.Index(fields=["type"], name="memes_type_170afd_idx"),
        ),
    ]
