# Generated by Django 5.1.5 on 2025-03-20 12:34

import config.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memecounter",
            name="viewers_count",
            field=models.PositiveIntegerField(default=0, help_text="조회자 수"),
        ),
        migrations.AddField(
            model_name="memecounter",
            name="views_count",
            field=models.PositiveIntegerField(default=0, help_text="조회 수"),
        ),
        migrations.CreateModel(
            name="MemeView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField(default=0)),
                (
                    "meme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meme_views",
                        to="meme.meme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meme_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "meme_view",
                "verbose_name_plural": "meme_views",
                "db_table": "meme_views",
                "indexes": [
                    models.Index(
                        fields=["meme", "user"], name="meme_views_meme_id_50721e_idx"
                    )
                ],
                "unique_together": {("meme", "user")},
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
