# Generated by Django 5.1.5 on 2025-03-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0003_memecounter_viewers_count_memecounter_views_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memecounter",
            name="meme",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meme_counter",
                to="meme.meme",
            ),
        ),
    ]
