# Generated by Django 5.1.7 on 2025-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0004_alter_memecounter_meme"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="original_title",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="original title"
            ),
        ),
        migrations.AlterField(
            model_name="meme",
            name="original_link",
            field=models.TextField(blank=True, null=True, verbose_name="original link"),
        ),
    ]
