# Generated by Django 5.1.7 on 2025-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0005_meme_original_title_alter_meme_original_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="original_link",
            field=models.URLField(blank=True, null=True, verbose_name="original link"),
        ),
    ]
