from __future__ import annotations

from typing import Protocol

from .entities import AbuseBlock


class AbuseRepository(Protocol):
    def initialize(self) -> None: ...
    def create(self, block: AbuseBlock) -> AbuseBlock: ...
    def active_for(self, identity_hash: str, conversation_id: str | None) -> AbuseBlock | None: ...
    def list(self, include_revoked: bool = True) -> list[AbuseBlock]: ...
    def revoke(self, block_id: str) -> AbuseBlock | None: ...
