# Generated by Django 6.0.3 on 2026-03-31 18:30

import common.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Achievement',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('code', models.CharField(max_length=100, unique=True, verbose_name='도전과제 코드')),
        ('name', models.CharField(max_length=100, verbose_name='도전과제 이름')),
        ('description', models.TextField(blank=True, default='', verbose_name='도전과제 설명')),
        (
          'category',
          models.CharField(
            choices=[('streak', '스트릭'), ('activity', '활동'), ('profile', '프로필'), ('interview', '인터뷰'), ('other', '기타')],
            default='other',
            max_length=30,
            verbose_name='도전과제 카테고리'
          )
        ),
        (
          'condition_type',
          models.CharField(
            choices=[('rule_group', '규칙 그룹')], default='rule_group', max_length=30, verbose_name='조건 타입'
          )
        ),
        ('condition_schema_version', models.PositiveSmallIntegerField(default=1, verbose_name='조건 스키마 버전')),
        ('condition_payload', models.JSONField(default=dict, verbose_name='도전과제 조건 DSL')),
        ('reward_payload', models.JSONField(default=dict, verbose_name='보상 정보')),
        ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
        ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='달성 가능 시작 시각')),
        ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='달성 가능 종료 시각')),
      ],
      options={
        'verbose_name': '도전과제',
        'verbose_name_plural': '도전과제 목록',
        'ordering': ['category', 'code'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='achievement_created_07dca5_idx'),
          models.Index(fields=['-updated_at'], name='achievement_updated_ceff40_idx'),
          models.Index(fields=['is_active', 'starts_at', 'ends_at', 'category'], name='achv_active_period_idx')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='UserAchievement',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('achieved_at', models.DateTimeField(verbose_name='달성 시각')),
        ('achievement_snapshot_payload', models.JSONField(blank=True, default=dict, verbose_name='달성 근거 스냅샷')),
        ('reward_claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='보상 수령 시각')),
        ('reward_claim_snapshot_payload', models.JSONField(blank=True, default=dict, verbose_name='보상 수령 스냅샷')),
        (
          'achievement',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='user_achievements',
            to='achievements.achievement',
            verbose_name='도전과제'
          )
        ),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='user_achievements',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': '사용자 도전과제 달성',
        'verbose_name_plural': '사용자 도전과제 달성 목록',
        'ordering': ['-created_at'],
        'get_latest_by': 'created_at',
        'abstract': False,
        'indexes': [
          models.Index(fields=['-created_at'], name='achievement_created_173a20_idx'),
          models.Index(fields=['-updated_at'], name='achievement_updated_c75e68_idx'),
          models.Index(fields=['user', '-achieved_at'], name='user_achv_user_achvd_idx')
        ],
        'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
