# Generated by Django 6.0.3 on 2026-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('achievements', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='Milestone',
      fields=[],
      options={
        'verbose_name': '마일스톤',
        'verbose_name_plural': '마일스톤 목록',
        'ordering': ['condition_payload__rules__0__target'],
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('achievements.achievement', ),
    ),
  ]
