from __future__ import annotations

from typing import Any, Protocol


class ConversationRepository(Protocol):
    def create(self, metadata: dict[str, Any] | None = None) -> str: ...
    def exists(self, conversation_id: str) -> bool: ...
    def messages(self, conversation_id: str, limit: int = 40) -> list[dict[str, Any]]: ...
    def append(
        self,
        conversation_id: str,
        role: str,
        content: str,
        model: str | None = None,
        sources: list[dict[str, Any]] | None = None,
    ) -> None: ...


class KnowledgeRepository(Protocol):
    def get(self, item_id: str) -> dict[str, Any] | None: ...
    def list(self, limit: int = 100, offset: int = 0) -> list[dict[str, Any]]: ...
    def create(self, values: dict[str, Any]) -> dict[str, Any]: ...
    def update(self, item_id: str, values: dict[str, Any]) -> dict[str, Any] | None: ...
    def delete(self, item_id: str) -> bool: ...
