from __future__ import annotations

from typing import Protocol


class ConversationRepository(Protocol):
    def create(self, metadata: dict | None = None) -> str: ...
    def exists(self, conversation_id: str) -> bool: ...
    def messages(self, conversation_id: str, limit: int = 40) -> list[dict]: ...
    def append(
        self,
        conversation_id: str,
        role: str,
        content: str,
        model: str | None = None,
        sources: list[dict] | None = None,
    ) -> None: ...


class KnowledgeRepository(Protocol):
    def get(self, item_id: str) -> dict | None: ...
    def list(self, limit: int = 100, offset: int = 0) -> list[dict]: ...
    def create(self, values: dict) -> dict: ...
    def update(self, item_id: str, values: dict) -> dict | None: ...
    def delete(self, item_id: str) -> bool: ...
