# Generated by Django 5.2.5 on 2025-09-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_city_alter_profile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.job",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="job_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.jobcategory",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mbti",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESTJ", "ESTJ"),
                    ("ESTP", "ESTP"),
                    ("ESFJ", "ESFJ"),
                    ("ESFP", "ESFP"),
                    ("ENFJ", "ENFJ"),
                    ("ENFP", "ENFP"),
                    ("ENTJ", "ENTJ"),
                    ("ENTP", "ENTP"),
                    ("ISTJ", "ISTJ"),
                    ("ISTP", "ISTP"),
                    ("ISFJ", "ISFJ"),
                    ("ISFP", "ISFP"),
                    ("INFJ", "INFJ"),
                    ("INFP", "INFP"),
                    ("INTJ", "INTJ"),
                    ("INTP", "INTP"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
