# Generated by Django 5.2.5 on 2025-09-17 05:49

import django.db.models.deletion
from django.db import migrations, models

import profiles.models.profile_image


class Migration(migrations.Migration):

    dependencies = [
        ("file_managers", "0001_initial"),
        ("profiles", "0003_alter_profile_job_alter_profile_job_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_images",
                        to="file_managers.image",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_images",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Image",
                "verbose_name_plural": "Profile Images",
                "db_table": "profile_images",
            },
            managers=[
                ("objects", profiles.models.profile_image.ProfileImageManager()),
            ],
        ),
    ]
