# Generated by Django 5.2.5 on 2025-09-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_managers", "0001_initial"),
        ("profiles", "0004_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_image",
                to="file_managers.image",
            ),
        ),
    ]
