# Generated by Django 5.2.5 on 2025-09-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_profileimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("자시", "자시 (23:30~1:30)"),
                    ("축시", "축시 (1:30~3:30)"),
                    ("인시", "인시 (3:30~5:30)"),
                    ("묘시", "묘시 (5:30~7:30)"),
                    ("진시", "진시 (7:30~9:30)"),
                    ("사시", "사시 (9:30~11:30)"),
                    ("오시", "오시 (11:30~13:30)"),
                    ("미시", "미시 (13:30~15:30)"),
                    ("신시", "신시 (15:30~17:30)"),
                    ("유시", "유시 (17:30~19:30)"),
                    ("술시", "술시 (19:30~21:30)"),
                    ("해시", "해시 (21:30~23:30)"),
                ],
                max_length=10,
                null=True,
                verbose_name="출생시",
            ),
        ),
    ]
