# Generated by Django 5.2.5 on 2025-09-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_managers", "0002_image_image_type"),
        ("profiles", "0006_profile_birth_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name="한줄 소개"),
        ),
        migrations.AddField(
            model_name="profile",
            name="one_liner",
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name="나의 한마디"),
        ),
        migrations.AddField(
            model_name="profile",
            name="proof_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_proof_image",
                to="file_managers.image",
                verbose_name="인증 사진",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tmi",
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name="나의 TMI"),
        ),
    ]
