# Generated by Django 5.2.5 on 2025-09-27 15:24

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profile_introduction_profile_one_liner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="job",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="job_category",
        ),
        migrations.CreateModel(
            name="JobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manual_job",
                    models.CharField(
                        blank=True,
                        help_text="직접 입력한 직업명",
                        max_length=100,
                        verbose_name="직접 입력 직업명",
                    ),
                ),
                (
                    "manual_job_category",
                    models.CharField(
                        blank=True,
                        help_text="직접 입력한 직군",
                        max_length=100,
                        verbose_name="직접 입력 직군",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="선택된 직업",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.job",
                        verbose_name="직업",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="선택된 직업 카테고리",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.jobcategory",
                        verbose_name="직업 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "직업 정보",
                "verbose_name_plural": "직업 정보",
                "db_table": "job_infos",
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="job_info",
            field=models.OneToOneField(
                blank=True,
                help_text="사용자의 직업 정보",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.jobinfo",
                verbose_name="직업 정보",
            ),
        ),
    ]
