# Generated by Django 5.2.5 on 2025-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_remove_profile_job_remove_profile_job_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive", "비활성"),
                    ("pending", "승인 대기"),
                    ("active", "승인 완료"),
                ],
                default="inactive",
                max_length=10,
                verbose_name="프로필 상태",
            ),
        ),
    ]
