# Generated by Django 5.2.5 on 2025-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('profiles', '0009_profile_status'),
  ]

  operations = [
    migrations.AlterField(
      model_name='profile',
      name='introduction',
      field=models.TextField(blank=True, max_length=300, null=True, verbose_name='나의 한마디'),
    ),
    migrations.AlterField(
      model_name='profile',
      name='one_liner',
      field=models.TextField(blank=True, max_length=50, null=True, verbose_name='한줄 소개'),
    ),
  ]
