# Generated by Django 5.2.5 on 2025-10-27 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model
import payments.models.ticket_product


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="이 상품의 판매 가격 (원)",
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="가격 (KRW)",
                    ),
                ),
                (
                    "discount_rate",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="표시용 할인율 (0-100)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="할인율 (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="이 상품의 판매 여부",
                        verbose_name="판매 활성화",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="상품 목록에서의 표시 순서 (작을수록 먼저 표시)",
                        verbose_name="표시 순서",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="이 상품으로 구매할 수 있는 티켓 수량",
                        unique=True,
                        verbose_name="티켓 수량",
                    ),
                ),
            ],
            options={
                "verbose_name": "티켓 상품",
                "verbose_name_plural": "티켓 상품 목록",
                "db_table": "ticket_products",
                "ordering": ["display_order", "quantity"],
            },
            managers=[
                ("objects", payments.models.ticket_product.TicketProductManager()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="주문 ID",
                    ),
                ),
                ("order_name", models.CharField(max_length=255, verbose_name="주문명")),
                ("amount", models.PositiveIntegerField(verbose_name="결제 금액")),
                (
                    "product_object_id",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="상품 ID"),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="결제 시점의 상품명 (캐싱)",
                        max_length=255,
                        verbose_name="상품명",
                    ),
                ),
                (
                    "ticket_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="티켓 상품인 경우에만 사용",
                        verbose_name="구매 티켓 수량",
                    ),
                ),
                (
                    "payment_key",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="결제 키",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="웹훅 검증용 Secret 값",
                        max_length=200,
                        null=True,
                        verbose_name="결제 Secret 키",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "결제 대기"),
                            ("IN_PROGRESS", "결제 진행 중"),
                            ("WAITING_FOR_DEPOSIT", "입금 대기"),
                            ("DONE", "결제 완료"),
                            ("CANCELED", "결제 취소"),
                            ("PARTIAL_CANCELED", "부분 취소"),
                            ("ABORTED", "결제 중단"),
                            ("EXPIRED", "결제 만료"),
                        ],
                        db_index=True,
                        default="READY",
                        max_length=20,
                        verbose_name="결제 상태",
                    ),
                ),
                (
                    "method",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="결제 수단"),
                ),
                (
                    "method_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="결제 수단 상세",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="승인 일시"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="요청 일시"),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, max_length=500, null=True, verbose_name="영수증 URL"),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="취소 일시"),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, null=True, verbose_name="취소 사유"),
                ),
                (
                    "canceled_amount",
                    models.PositiveIntegerField(default=0, verbose_name="취소된 금액"),
                ),
                (
                    "virtual_account_bank",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="가상계좌 은행",
                    ),
                ),
                (
                    "virtual_account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="가상계좌 번호",
                    ),
                ),
                (
                    "virtual_account_holder_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="가상계좌 예금주",
                    ),
                ),
                (
                    "virtual_account_due_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="가상계좌 입금 기한"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="고객 이메일",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="고객 이름"),
                ),
                (
                    "customer_mobile_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="고객 휴대폰 번호",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, null=True, verbose_name="원본 응답 데이터"),
                ),
                (
                    "fail_code",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="실패 코드"),
                ),
                (
                    "fail_message",
                    models.TextField(blank=True, null=True, verbose_name="실패 메시지"),
                ),
                (
                    "product_content_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(("app_label", "payments")),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="상품 타입",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제 목록",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "결제"),
                            ("CANCEL", "취소"),
                            ("PARTIAL_CANCEL", "부분 취소"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="거래 유형",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="거래 금액")),
                (
                    "transaction_key",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="거래 키",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="성공 여부"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="사유"),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, null=True, verbose_name="원본 응답 데이터"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.payment",
                        verbose_name="결제",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 거래",
                "verbose_name_plural": "결제 거래 목록",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
    ]
