# Generated by Django 5.2.7 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('companies', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='Market',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('name', models.CharField(max_length=255, verbose_name='시장명')),
        (
          'code',
          models.CharField(
            choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=50, unique=True, verbose_name='시장 코드'
          )
        ),
        (
          'country',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='markets',
            to='companies.country',
            verbose_name='국가'
          )
        ),
      ],
      options={
        'verbose_name': 'Market',
        'verbose_name_plural': 'Markets',
        'db_table': 'markets',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='Stock',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('code', models.CharField(max_length=100, unique=True, verbose_name='종목 코드 (Ticker)')),
        ('name', models.CharField(max_length=255, verbose_name='종목명')),
        (
          'category',
          models.CharField(
            choices=[
              ('common', '보통주'), ('preferred', '우선주'), ('old_preferred', '구형 우선주'), ('new_preferred', '신형 우선주'),
              ('other', '기타')
            ],
            default='common',
            max_length=20,
            verbose_name='주식 종류'
          )
        ),
        ('is_primary', models.BooleanField(default=False, verbose_name='대표 주식 여부')),
        ('is_listed', models.BooleanField(default=True, verbose_name='상장 여부')),
        ('listed_date', models.DateField(blank=True, null=True, verbose_name='상장일')),
        ('delisted_date', models.DateField(blank=True, null=True, verbose_name='상장폐지일')),
        (
          'currency',
          models.CharField(
            choices=[
              ('KRW', '대한민국 원'), ('USD', '미국 달러'), ('EUR', '유로'), ('JPY', '일본 엔'), ('GBP', '영국 파운드'), ('CNY', '중국 위안'),
              ('HKD', '홍콩 달러'), ('AUD', '호주 달러'), ('CAD', '캐나다 달러'), ('CHF', '스위스 프랑')
            ],
            default='KRW',
            max_length=10,
            verbose_name='통화'
          )
        ),
        ('lot_size', models.IntegerField(default=1, verbose_name='거래 단위')),
        (
          'company',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='stocks',
            to='companies.company',
            verbose_name='회사'
          )
        ),
        (
          'market',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='stocks.market', verbose_name='시장'
          )
        ),
      ],
      options={
        'verbose_name': 'Stock',
        'verbose_name_plural': 'Stocks',
        'db_table': 'stocks',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='StockPrice',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('trade_date', models.DateField(verbose_name='거래일')),
        ('close_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='종가')),
        ('diff', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='전일 대비')),
        ('change_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='등락률 (%)')),
        ('open_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='시가')),
        ('high_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='고가')),
        ('low_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='저가')),
        ('volume', models.BigIntegerField(verbose_name='거래량')),
        ('value', models.BigIntegerField(verbose_name='거래대금')),
        ('market_cap', models.BigIntegerField(verbose_name='시가총액')),
        ('shares', models.BigIntegerField(verbose_name='상장주식수')),
        (
          'market',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='stock_prices',
            to='stocks.market',
            verbose_name='시장'
          )
        ),
        (
          'stock',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock', verbose_name='종목'
          )
        ),
      ],
      options={
        'verbose_name': 'Stock Price',
        'verbose_name_plural': 'Stock Prices',
        'db_table': 'stock_prices',
        'ordering': ['-trade_date', 'stock'],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='DelistedStock',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('isu_cd', models.CharField(help_text='ISU_CD', max_length=20, verbose_name='종목 코드')),
        ('isu_nm', models.CharField(help_text='ISU_NM', max_length=255, verbose_name='종목명')),
        (
          'market_name_raw',
          models.CharField(
            blank=True,
            default='',
            help_text='MKT_NM 원본 값 (KOSPI, KOSDAQ, KONEX 등)',
            max_length=20,
            verbose_name='원본 시장 구분'
          )
        ),
        (
          'secugrp_nm',
          models.CharField(
            blank=True,
            default='',
            help_text='SECUGRP_NM (주권, 수익증권, 신주인수권증서, 신주인수권증권 등)',
            max_length=50,
            verbose_name='증권 그룹'
          )
        ),
        (
          'kind_stkcert_tp_nm',
          models.CharField(
            blank=True, default='', help_text='KIND_STKCERT_TP_NM (보통주, 우선주 등)', max_length=50, verbose_name='주식 종류'
          )
        ),
        ('list_dd', models.DateField(help_text='LIST_DD', verbose_name='상장일')),
        ('delist_dd', models.DateField(help_text='DELIST_DD', verbose_name='상장폐지일')),
        (
          'delist_rsn_dsc',
          models.TextField(blank=True, default='', help_text='DELIST_RSN_DSC', verbose_name='상장폐지 사유')
        ),
        (
          'arrantrd_mktact_enforce_dd',
          models.DateField(blank=True, help_text='ARRANTRD_MKTACT_ENFORCE_DD', null=True, verbose_name='정리매매 시작일')
        ),
        (
          'arrantrd_end_dd',
          models.DateField(blank=True, help_text='ARRANTRD_END_DD', null=True, verbose_name='정리매매 종료일')
        ),
        (
          'idx_ind_nm',
          models.CharField(blank=True, default='', help_text='IDX_IND_NM', max_length=100, verbose_name='업종명')
        ),
        ('parval', models.CharField(blank=True, default='', help_text='PARVAL', max_length=50, verbose_name='액면가')),
        (
          'list_shrs',
          models.CharField(
            blank=True, default='', help_text='LIST_SHRS (쉼표 포함 문자열)', max_length=50, verbose_name='상장주식수'
          )
        ),
        (
          'to_isu_srt_cd',
          models.CharField(blank=True, default='', help_text='TO_ISU_SRT_CD', max_length=20, verbose_name='전환 종목 코드')
        ),
        (
          'to_isu_abbrv',
          models.CharField(blank=True, default='', help_text='TO_ISU_ABBRV', max_length=255, verbose_name='전환 종목 약어')
        ),
        (
          'raw',
          models.JSONField(blank=True, default=dict, help_text='KRX API에서 받은 원본 JSON 데이터', verbose_name='원본 데이터')
        ),
        (
          'market',
          models.ForeignKey(
            blank=True,
            help_text='KOSPI 또는 KOSDAQ 시장',
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='delisted_stocks',
            to='stocks.market',
            verbose_name='시장'
          )
        ),
      ],
      options={
        'verbose_name':
        'Delisted Stock',
        'verbose_name_plural':
        'Delisted Stocks',
        'db_table':
        'delisted_stocks',
        'indexes': [
          models.Index(fields=['isu_cd'], name='idx_delisted_isu_cd'),
          models.Index(fields=['market'], name='idx_delisted_market'),
          models.Index(fields=['delist_dd'], name='idx_delisted_delist_dd'),
          models.Index(fields=['-delist_dd'], name='idx_delisted_delist_dd_desc')
        ],
        'constraints': [
          models.UniqueConstraint(
            fields=('isu_cd', 'list_dd', 'delist_dd'), name='unique_delisted_stock_isu_list_delist'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['name'], name='idx_stock_name'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['market', 'company'], name='idx_stock_company_market'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['market'], name='idx_stock_market'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['is_primary', 'company'], name='idx_stock_is_primary'),
    ),
    migrations.AddIndex(
      model_name='stockprice',
      index=models.Index(fields=['stock', 'trade_date'], name='idx_stock_date'),
    ),
    migrations.AddIndex(
      model_name='stockprice',
      index=models.Index(fields=['market', 'trade_date'], name='idx_market_date'),
    ),
    migrations.AddIndex(
      model_name='stockprice',
      index=models.Index(fields=['trade_date'], name='idx_trade_date'),
    ),
    migrations.AddConstraint(
      model_name='stockprice',
      constraint=models.UniqueConstraint(
        fields=('trade_date', 'market', 'stock'), name='unique_trade_date_market_stock'
      ),
    ),
  ]
