# Generated by Django 5.2.7 on 2025-12-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
    ('stocks', '0001_initial'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='delistedstock',
      name='market_name_raw',
    ),
  ]
