# Generated by Django 5.2.7 on 2025-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('companies', '0001_initial'),
    ('stocks', '0002_remove_delistedstock_market_name_raw'),
  ]

  operations = [
    migrations.RemoveIndex(
      model_name='stock',
      name='idx_stock_market',
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['is_listed'], name='idx_stock_is_listed'),
    ),
  ]
