# Generated by Django 5.2.7 on 2025-12-04 10:23

from django.db import migrations

import stocks.models.stock


class Migration(migrations.Migration):

  dependencies = [
    ('stocks', '0003_remove_stock_idx_stock_market_and_more'),
  ]

  operations = [
    migrations.AlterModelManagers(
      name='stock',
      managers=[
        ('objects', stocks.models.stock.StockManager()),
      ],
    ),
  ]
