# Generated by Django 5.2.7 on 2025-12-05 09:34

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ('companies', '0003_alter_company_primary_stock_code'),
    ('financial_statements', '0002_rawfinancialstatementaccount_and_more'),
    ('stocks', '0004_alter_stock_managers'),
  ]

  operations = [
    migrations.CreateModel(
      name='DerivedIndicator',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('fiscal_year', models.PositiveIntegerField(verbose_name='회계연도')),
        ('fiscal_quarter', models.PositiveSmallIntegerField(verbose_name='분기')),
        (
          'reference_price',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='지표 계산에 사용된 주가 (분기 말일 종가)',
            max_digits=20,
            null=True,
            verbose_name='기준 주가'
          )
        ),
        ('reference_date', models.DateField(blank=True, help_text='기준 주가의 날짜', null=True, verbose_name='기준일')),
        (
          'market_cap',
          models.DecimalField(
            blank=True, decimal_places=2, help_text='기준일 기준 시가총액', max_digits=24, null=True, verbose_name='시가총액'
          )
        ),
        (
          'per',
          models.DecimalField(
            blank=True,
            decimal_places=4,
            help_text='주가수익비율 (Price / EPS)',
            max_digits=12,
            null=True,
            verbose_name='PER'
          )
        ),
        (
          'eps',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='주당순이익 (Earnings Per Share)',
            max_digits=20,
            null=True,
            verbose_name='EPS'
          )
        ),
        (
          'pbr',
          models.DecimalField(
            blank=True,
            decimal_places=4,
            help_text='주가순자산비율 (Price / BPS)',
            max_digits=12,
            null=True,
            verbose_name='PBR'
          )
        ),
        (
          'bps',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='주당순자산 (Book value Per Share)',
            max_digits=20,
            null=True,
            verbose_name='BPS'
          )
        ),
        (
          'roe',
          models.DecimalField(
            blank=True,
            decimal_places=4,
            help_text='자기자본이익률 (Net Income / Equity * 100)',
            max_digits=10,
            null=True,
            verbose_name='ROE (%)'
          )
        ),
        (
          'roa',
          models.DecimalField(
            blank=True,
            decimal_places=4,
            help_text='총자산이익률 (Net Income / Total Assets * 100)',
            max_digits=10,
            null=True,
            verbose_name='ROA (%)'
          )
        ),
        (
          'dividend_yield',
          models.DecimalField(
            blank=True,
            decimal_places=4,
            help_text='배당수익률 (DPS / Price * 100)',
            max_digits=10,
            null=True,
            verbose_name='배당수익률 (%)'
          )
        ),
        (
          'dps',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='주당배당금 (Dividend Per Share)',
            max_digits=20,
            null=True,
            verbose_name='DPS'
          )
        ),
        (
          'net_income',
          models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='당기순이익')
        ),
        (
          'total_equity',
          models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='자본총계')
        ),
        (
          'total_assets',
          models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, verbose_name='자산총계')
        ),
        ('total_shares', models.BigIntegerField(blank=True, null=True, verbose_name='총 발행주식수')),
        (
          'calculation_notes',
          models.JSONField(blank=True, default=dict, help_text='계산 과정에서 발생한 특이사항이나 메모', verbose_name='계산 메모')
        ),
        (
          'company',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='derived_indicators',
            to='companies.company',
            verbose_name='회사'
          )
        ),
        (
          'financial_statement',
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='derived_indicators',
            to='financial_statements.financialstatement',
            verbose_name='재무제표'
          )
        ),
        (
          'stock',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='derived_indicators',
            to='stocks.stock',
            verbose_name='종목'
          )
        ),
      ],
      options={
        'verbose_name':
        '파생지표',
        'verbose_name_plural':
        '파생지표',
        'db_table':
        'derived_indicators',
        'ordering': ['-fiscal_year', '-fiscal_quarter', 'stock'],
        'indexes': [
          models.Index(fields=['stock', '-fiscal_year', '-fiscal_quarter'], name='idx_di_stock_period'),
          models.Index(fields=['company', '-fiscal_year', '-fiscal_quarter'], name='idx_di_company_period'),
          models.Index(fields=['fiscal_year', 'fiscal_quarter'], name='idx_di_period')
        ],
        'constraints': [
          models.UniqueConstraint(
            fields=('stock', 'company', 'fiscal_year', 'fiscal_quarter'), name='unique_stock_company_year_quarter'
          )
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
