# Generated by Django 5.2.7 on 2025-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('companies', '0003_alter_company_primary_stock_code'),
    ('stocks', '0005_derivedindicator'),
  ]

  operations = [
    migrations.AddField(
      model_name='stock',
      name='latest_bps',
      field=models.DecimalField(
        blank=True, decimal_places=2, help_text='가장 최근 분기의 BPS', max_digits=20, null=True, verbose_name='최신 BPS'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_dividend_yield',
      field=models.DecimalField(
        blank=True,
        decimal_places=4,
        help_text='가장 최근 분기의 배당수익률',
        max_digits=10,
        null=True,
        verbose_name='최신 배당수익률 (%)'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_dps',
      field=models.DecimalField(
        blank=True, decimal_places=2, help_text='가장 최근 분기의 DPS', max_digits=20, null=True, verbose_name='최신 DPS'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_eps',
      field=models.DecimalField(
        blank=True, decimal_places=2, help_text='가장 최근 분기의 EPS', max_digits=20, null=True, verbose_name='최신 EPS'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_indicator_updated_at',
      field=models.DateTimeField(blank=True, help_text='최신 파생지표가 캐시된 시각', null=True, verbose_name='최신 지표 업데이트 시각'),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_pbr',
      field=models.DecimalField(
        blank=True, decimal_places=4, help_text='가장 최근 분기의 PBR', max_digits=12, null=True, verbose_name='최신 PBR'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_per',
      field=models.DecimalField(
        blank=True, decimal_places=4, help_text='가장 최근 분기의 PER', max_digits=12, null=True, verbose_name='최신 PER'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_roa',
      field=models.DecimalField(
        blank=True, decimal_places=4, help_text='가장 최근 분기의 ROA', max_digits=10, null=True, verbose_name='최신 ROA (%)'
      ),
    ),
    migrations.AddField(
      model_name='stock',
      name='latest_roe',
      field=models.DecimalField(
        blank=True, decimal_places=4, help_text='가장 최근 분기의 ROE', max_digits=10, null=True, verbose_name='최신 ROE (%)'
      ),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['latest_per'], name='idx_stock_latest_per'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['latest_pbr'], name='idx_stock_latest_pbr'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['latest_roe'], name='idx_stock_latest_roe'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['latest_roa'], name='idx_stock_latest_roa'),
    ),
    migrations.AddIndex(
      model_name='stock',
      index=models.Index(fields=['latest_dividend_yield'], name='idx_stock_latest_div_yield'),
    ),
  ]
