# Generated by Django 5.2.5 on 2025-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_managers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("profile_images", "프로필 이미지"),
                    ("proof_images", "인증 사진"),
                    ("images", "일반 이미지"),
                ],
                default="images",
                max_length=20,
                verbose_name="이미지 타입",
            ),
        ),
    ]
