# Generated by Django 5.1.5 on 2025-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="link",
            field=models.TextField(blank=True, null=True, verbose_name="영상 링크"),
        ),
        migrations.AddField(
            model_name="video",
            name="link_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Youtube", "Youtube"),
                    ("Facebook", "Facebook"),
                    ("Instagram", "Instagram"),
                    ("X", "X"),
                    ("Vimeo", "Vimeo"),
                ],
                max_length=20,
                null=True,
                verbose_name="링크 타입 (영상 링크 출처)",
            ),
        ),
    ]
