# Generated by Django 5.1.5 on 2025-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0002_video_link_video_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="파일"
            ),
        ),
    ]
