# Generated by Django 5.1.5 on 2025-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0003_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="영상 링크"),
        ),
    ]
