# Generated by Django 5.1.7 on 2025-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0004_alter_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="web_url",
            field=models.URLField(
                blank=True,
                help_text="웹에서 접근할 수 있는 URL, 파일이 없는 경우 사용됩니다.",
                max_length=500,
                null=True,
                verbose_name="웹 URL",
            ),
        ),
    ]
