# Generated by Django 5.2.5 on 2025-11-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import action_trackings.models.profile_view_tracking

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('contenttypes', '0002_remove_content_type_name'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='ActionTracking',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('action_type',
         models.CharField(choices=[('profile_view', '프로필 조회')], db_index=True, max_length=50, verbose_name='액션 타입')),
        ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='객체 ID')),
        ('metadata',
         models.JSONField(blank=True, default=dict, help_text='액션과 관련된 추가 정보를 JSON 형태로 저장', verbose_name='메타데이터')),
        ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
        ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
        ('content_type',
         models.ForeignKey(blank=True,
                           null=True,
                           on_delete=django.db.models.deletion.CASCADE,
                           to='contenttypes.contenttype',
                           verbose_name='컨텐츠 타입')),
        ('user',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='action_trackings',
                           to=settings.AUTH_USER_MODEL,
                           verbose_name='사용자')),
      ],
      options={
        'verbose_name': '액션 트래킹',
        'verbose_name_plural': '액션 트래킹',
        'db_table': 'action_trackings',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='ProfileViewTracking',
      fields=[],
      options={
        'verbose_name': '프로필 조회 트래킹',
        'verbose_name_plural': '프로필 조회 트래킹',
        'proxy': True,
        'indexes': [],
        'constraints': [],
      },
      bases=('action_trackings.actiontracking', ),
      managers=[
        ('objects', action_trackings.models.profile_view_tracking.ProfileViewTrackingManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='actiontracking',
      index=models.Index(fields=['user', 'action_type', '-created_at'], name='action_trac_user_id_ffa2cf_idx'),
    ),
    migrations.AddIndex(
      model_name='actiontracking',
      index=models.Index(fields=['action_type', '-created_at'], name='action_trac_action__98da7e_idx'),
    ),
    migrations.AddIndex(
      model_name='actiontracking',
      index=models.Index(fields=['content_type', 'object_id'], name='action_trac_content_82efe1_idx'),
    ),
  ]
