# Generated by Django 5.2.7 on 2025-12-04 07:35

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('companies', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='CompanyDisclosure',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('receipt_no', models.CharField(max_length=30)),
        ('title', models.CharField(max_length=500)),
        ('published_at', models.DateTimeField()),
        ('text_body', models.TextField(blank=True)),
        ('html_body', models.TextField(blank=True)),
        ('disclosure_type', models.CharField(blank=True, max_length=100)),
        ('source_url', models.URLField(blank=True, max_length=500)),
        (
          'company',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='companies.company'
          )
        ),
      ],
      options={
        'verbose_name':
        'Company Disclosure',
        'verbose_name_plural':
        'Company Disclosures',
        'db_table':
        'company_disclosures',
        'indexes': [
          models.Index(fields=['company', '-published_at'], name='company_dis_company_46dd38_idx'),
          models.Index(fields=['receipt_no'], name='company_dis_receipt_a1c089_idx')
        ],
        'constraints': [models.UniqueConstraint(fields=('company', 'receipt_no'), name='unique_company_receipt_no')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
