# Generated by Django 5.2.7 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('companies', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='FinancialStatement',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('fiscal_year', models.PositiveIntegerField()),
        ('fiscal_quarter', models.PositiveSmallIntegerField()),
        (
          'report_type',
          models.CharField(
            choices=[('q1', '1분기보고서'), ('half', '반기보고서'), ('q3', '3분기보고서'), ('annual', '사업보고서')], max_length=16
          )
        ),
        ('currency', models.CharField(default='KRW', max_length=10)),
        ('is_consolidated', models.BooleanField(default=True)),
        ('submission_date', models.DateField(blank=True, null=True)),
        ('receipt_no', models.CharField(blank=True, max_length=20)),
        ('source', models.CharField(blank=True, choices=[('CFS', '연결재무제표'), ('OFS', '재무제표(개별)')], max_length=3)),
        (
          'company',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='companies.company'
          )
        ),
      ],
      options={
        'verbose_name': '재무제표',
        'verbose_name_plural': '재무제표',
        'db_table': 'financial_statements',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='FinancialStatementAccount',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'account_id',
          models.CharField(
            help_text='DART API에서 제공하는 표준계정코드 (예: ifrs_CurrentAssets)', max_length=255, verbose_name='계정과목 ID'
          )
        ),
        (
          'account_name',
          models.CharField(db_index=True, help_text='계정과목 이름 (예: 유동자산, 매출채권)', max_length=255, verbose_name='계정과목명')
        ),
        (
          'account_category',
          models.CharField(
            blank=True,
            default='',
            help_text='BS(재무상태표), IS(손익계산서), CIS(포괄손익계산서), CF(현금흐름표), SCE(자본변동표)',
            max_length=32,
            verbose_name='계정과목 분류'
          )
        ),
        (
          'category_name',
          models.CharField(
            blank=True, default='', help_text='sj_nm (예: 재무상태표, 손익계산서)', max_length=255, verbose_name='재무제표 구분명'
          )
        ),
        (
          'account_detail',
          models.CharField(blank=True, default='', help_text='account_detail', max_length=255, verbose_name='계정과목 상세')
        ),
      ],
      options={
        'verbose_name':
        '재무제표 계정과목',
        'verbose_name_plural':
        '재무제표 계정과목',
        'db_table':
        'financial_statement_accounts',
        'indexes': [
          models.Index(fields=['account_id'], name='idx_fsa_account_id'),
          models.Index(fields=['account_name'], name='idx_fsa_account_name')
        ],
        'constraints': [models.UniqueConstraint(fields=('account_id', 'account_name'), name='unique_account_id_name')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='FinancialStatementItem',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'current_amount',
          models.DecimalField(
            blank=True, decimal_places=2, help_text='thstrm_amount', max_digits=24, null=True, verbose_name='당기금액'
          )
        ),
        (
          'cumulative_amount',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='thstrm_add_amount',
            max_digits=24,
            null=True,
            verbose_name='당기누적금액'
          )
        ),
        ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
        ('raw', models.JSONField(blank=True, default=dict, verbose_name='원본 데이터')),
        (
          'account',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='items',
            to='financial_statements.financialstatementaccount',
            verbose_name='계정과목'
          )
        ),
        (
          'statement',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='items',
            to='financial_statements.financialstatement',
            verbose_name='재무제표'
          )
        ),
      ],
      options={
        'verbose_name': '재무제표 항목',
        'verbose_name_plural': '재무제표 항목',
        'db_table': 'financial_statement_items',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.AddIndex(
      model_name='financialstatement',
      index=models.Index(fields=['company', '-fiscal_year', '-fiscal_quarter'], name='idx_fs_company_period'),
    ),
    migrations.AddIndex(
      model_name='financialstatement',
      index=models.Index(fields=['company', 'source'], name='idx_fs_company_source'),
    ),
    migrations.AddConstraint(
      model_name='financialstatement',
      constraint=models.UniqueConstraint(
        fields=('company', 'fiscal_year', 'fiscal_quarter', 'report_type', 'source'),
        name='unique_company_year_quarter_report_source'
      ),
    ),
    migrations.AddIndex(
      model_name='financialstatementitem',
      index=models.Index(fields=['statement', 'account'], name='idx_fsi_statement_account'),
    ),
    migrations.AddConstraint(
      model_name='financialstatementitem',
      constraint=models.UniqueConstraint(fields=('statement', 'account'), name='unique_statement_account'),
    ),
  ]
