# Generated by Django 5.2.7 on 2025-12-04 14:05

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ('companies', '0003_alter_company_primary_stock_code'),
    ('financial_statements', '0001_initial'),
  ]

  operations = [
    migrations.CreateModel(
      name='RawFinancialStatementAccount',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'account_id',
          models.CharField(
            help_text='DART API에서 제공하는 표준계정코드 (예: ifrs_CurrentAssets)', max_length=255, verbose_name='계정과목 ID'
          )
        ),
        (
          'account_name',
          models.CharField(db_index=True, help_text='계정과목 이름 (예: 유동자산, 매출채권)', max_length=255, verbose_name='계정과목명')
        ),
        (
          'account_category',
          models.CharField(
            blank=True,
            default='',
            help_text='BS(재무상태표), IS(손익계산서), CIS(포괄손익계산서), CF(현금흐름표), SCE(자본변동표)',
            max_length=32,
            verbose_name='계정과목 분류'
          )
        ),
        (
          'category_name',
          models.CharField(
            blank=True, default='', help_text='sj_nm (예: 재무상태표, 손익계산서)', max_length=255, verbose_name='재무제표 구분명'
          )
        ),
        (
          'account_detail',
          models.CharField(blank=True, default='', help_text='account_detail', max_length=255, verbose_name='계정과목 상세')
        ),
      ],
      options={
        'verbose_name':
        '원본 재무제표 계정과목',
        'verbose_name_plural':
        '원본 재무제표 계정과목',
        'db_table':
        'raw_financial_statement_accounts',
        'indexes': [
          models.Index(fields=['account_id'], name='idx_raw_fsa_account_id'),
          models.Index(fields=['account_name'], name='idx_raw_fsa_account_name')
        ],
        'constraints':
        [models.UniqueConstraint(fields=('account_id', 'account_name'), name='unique_raw_account_id_name')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='FinancialStatementItemMappingRule',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'source_account_id',
          models.CharField(
            help_text='변환 전 계정과목 ID (예: ifrs-full_CurrentAssets 또는 -표준계정코드 미사용-)',
            max_length=255,
            verbose_name='원본 계정과목 ID'
          )
        ),
        (
          'source_account_name',
          models.CharField(help_text='변환 전 계정과목명 (예: 유동자산)', max_length=255, verbose_name='원본 계정과목명')
        ),
        (
          'target_account_id',
          models.CharField(help_text='변환 후 계정과목 ID (예: ifrs_CurrentAssets)', max_length=255, verbose_name='대상 계정과목 ID')
        ),
        (
          'target_account_name',
          models.CharField(help_text='변환 후 계정과목명 (예: 유동자산)', max_length=255, verbose_name='대상 계정과목명')
        ),
        (
          'priority',
          models.IntegerField(default=0, help_text='숫자가 높을수록 우선 적용됩니다 (회사별 규칙이 전체 규칙보다 우선)', verbose_name='우선순위')
        ),
        ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
        ('description', models.TextField(blank=True, default='', verbose_name='설명')),
        (
          'company',
          models.ForeignKey(
            blank=True,
            help_text='null이면 전체 회사에 적용됩니다',
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='financial_statement_mapping_rules',
            to='companies.company',
            verbose_name='대상 회사'
          )
        ),
      ],
      options={
        'verbose_name':
        '재무제표 항목 매핑 규칙',
        'verbose_name_plural':
        '재무제표 항목 매핑 규칙',
        'db_table':
        'financial_statement_item_mapping_rules',
        'ordering': ['-priority', 'company', 'source_account_id'],
        'indexes': [
          models.Index(fields=['company'], name='idx_fsimr_company'),
          models.Index(fields=['source_account_id'], name='idx_fsimr_src_id'),
          models.Index(fields=['source_account_name'], name='idx_fsimr_src_name'),
          models.Index(fields=['is_active'], name='idx_fsimr_active'),
          models.Index(fields=['-priority'], name='idx_fsimr_priority')
        ],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='RawFinancialStatementItem',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        (
          'current_amount',
          models.DecimalField(
            blank=True, decimal_places=2, help_text='thstrm_amount', max_digits=24, null=True, verbose_name='당기금액'
          )
        ),
        (
          'cumulative_amount',
          models.DecimalField(
            blank=True,
            decimal_places=2,
            help_text='thstrm_add_amount',
            max_digits=24,
            null=True,
            verbose_name='당기누적금액'
          )
        ),
        ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
        ('raw', models.JSONField(blank=True, default=dict, verbose_name='원본 데이터')),
        (
          'account',
          models.ForeignKey(
            on_delete=django.db.models.deletion.PROTECT,
            related_name='raw_items',
            to='financial_statements.rawfinancialstatementaccount',
            verbose_name='원본 계정과목'
          )
        ),
        (
          'statement',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='raw_items',
            to='financial_statements.financialstatement',
            verbose_name='재무제표'
          )
        ),
      ],
      options={
        'verbose_name':
        '원본 재무제표 항목',
        'verbose_name_plural':
        '원본 재무제표 항목',
        'db_table':
        'raw_financial_statement_items',
        'indexes': [
          models.Index(fields=['statement'], name='idx_raw_fsi_statement'),
          models.Index(fields=['account'], name='idx_raw_fsi_account')
        ],
        'constraints': [models.UniqueConstraint(fields=('statement', 'account'), name='unique_raw_statement_account')],
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
