# Generated by Django 5.2.7 on 2025-10-24 17:26

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="4자리 이상의 영문과 숫자 조합",
                max_length=20,
                unique=True,
                validators=[users.validators.validate_username],
            ),
        ),
    ]
