# Generated by Django 5.2.7 on 2025-11-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_child"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        help_text="BOT 인증을 위한 토큰 문자열", max_length=100, unique=True, verbose_name="토큰"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="이 토큰과 연관된 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOT 토큰",
                "verbose_name_plural": "BOT 토큰",
                "db_table": "bot_tokens",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
    ]
