# Generated by Django 5.2.7 on 2025-12-04 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('stocks', '0004_alter_stock_managers'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Watchlist',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('name', models.CharField(max_length=255, verbose_name='관심목록명')),
        ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
        (
          'user',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='watchlists',
            to=settings.AUTH_USER_MODEL,
            verbose_name='사용자'
          )
        ),
      ],
      options={
        'verbose_name': 'Watchlist',
        'verbose_name_plural': 'Watchlists',
        'db_table': 'watchlists',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='WatchlistItem',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
        (
          'stock',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='watchlist_items',
            to='stocks.stock',
            verbose_name='주식'
          )
        ),
        (
          'watchlist',
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name='items',
            to='watchlists.watchlist',
            verbose_name='관심목록'
          )
        ),
      ],
      options={
        'verbose_name': 'Watchlist Item',
        'verbose_name_plural': 'Watchlist Items',
        'db_table': 'watchlist_items',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
