# Generated by Django 5.2.5 on 2025-09-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model
import matchmakings.models.pre_matching_score


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0007_userapproval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="태그 이름")),
            ],
            options={
                "verbose_name": "Compatibility Tag",
                "verbose_name_plural": "Compatibility Tags",
                "db_table": "compatibility_tags",
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="PreMatching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CALCULATING", "Calculating"),
                            ("COMPLETED", "Completed"),
                            ("RECOMMENDED", "Recommended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "matching_reason",
                    models.TextField(blank=True, null=True, verbose_name="매칭 사유"),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마지막 계산 시간"),
                ),
                (
                    "compatibility_score",
                    models.IntegerField(default=0, verbose_name="궁합 점수"),
                ),
                (
                    "female_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="female_pre_matchings",
                        to="users.femaleuser",
                    ),
                ),
                (
                    "male_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="male_pre_matchings",
                        to="users.maleuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre Matching",
                "verbose_name_plural": "Pre Matchings",
                "db_table": "pre_matchings",
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="PreMatchingCompatibilityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compatibility_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_matching_compatibility_tags",
                        to="matchmakings.compatibilitytag",
                    ),
                ),
                (
                    "pre_matching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_matching_compatibility_tags",
                        to="matchmakings.prematching",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre Matching Compatibility Tag",
                "verbose_name_plural": "Pre Matching Compatibility Tags",
                "db_table": "pre_matching_compatibility_tags",
                "unique_together": {("pre_matching", "compatibility_tag")},
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.AddField(
            model_name="prematching",
            name="compatibility_tags",
            field=models.ManyToManyField(
                related_name="pre_matchings",
                through="matchmakings.PreMatchingCompatibilityTag",
                to="matchmakings.compatibilitytag",
            ),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("referred_at", models.DateTimeField(verbose_name="추천 일시")),
                (
                    "referred_algorithm",
                    models.CharField(max_length=255, verbose_name="추천 알고리즘"),
                ),
                (
                    "referral_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="추천된 사용자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="추천을 받은 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "db_table": "referrals",
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="prematching",
            unique_together={("male_user", "female_user")},
        ),
        migrations.CreateModel(
            name="PreMatchingScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "algorithm_category",
                    models.CharField(
                        choices=matchmakings.models.pre_matching_score.get_algorithm_choices,
                        default=matchmakings.models.pre_matching_score.get_default_algorithm,
                        max_length=20,
                    ),
                ),
                (
                    "prematching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_matching_scores",
                        to="matchmakings.prematching",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre Matching Score",
                "verbose_name_plural": "Pre Matching Scores",
                "db_table": "pre_matching_scores",
                "unique_together": {("prematching", "algorithm_category")},
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Matching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket_amount",
                    models.PositiveIntegerField(
                        help_text="해당 매칭을 통해 사용된 티켓의 수",
                        verbose_name="사용된 티켓 수량",
                    ),
                ),
                ("sent_at", models.DateTimeField(verbose_name="전송 일시")),
                (
                    "received_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="수신 일시"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="거절 일시"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchings_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="매칭 수신자",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchings_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="매칭 요청자",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchings",
                        to="matchmakings.referral",
                        verbose_name="추천 현황",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matching",
                "verbose_name_plural": "Matchings",
                "db_table": "matchings",
                "constraints": [models.UniqueConstraint(fields=("sender", "receiver"), name="unique_sender_receiver")],
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
    ]
