# Generated by Django 5.2.5 on 2025-10-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchmakings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matching",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="만료된 일시"),
        ),
    ]
