# Generated by Django 5.2.5 on 2025-10-31 17:40

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ("matchmakings", "0002_matching_expired_at"),
  ]

  operations = [
    migrations.CreateModel(
      name="ReferralConversation",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "conversation_messages",
          models.JSONField(
            help_text="ConversationMessage 형태의 대화 메시지 리스트",
            verbose_name="대화 메시지",
          ),
        ),
        (
          "referral",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="conversation",
            to="matchmakings.referral",
            verbose_name="추천",
          ),
        ),
      ],
      options={
        "verbose_name": "Referral Conversation",
        "verbose_name_plural": "Referral Conversations",
        "db_table": "referral_conversations",
      },
      managers=[
        ("objects", common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
