# Generated by Django 5.2.5 on 2025-11-04 16:32

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ('matchmakings', '0003_referralconversation'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='prematching',
      name='compatibility_tags',
    ),
    migrations.AddField(
      model_name='referral',
      name='compatibility_score',
      field=models.IntegerField(default=0, verbose_name='궁합 점수'),
    ),
    migrations.AddField(
      model_name='referral',
      name='synergy_generation_status',
      field=models.CharField(choices=[('PENDING', '초기화됨'), ('GENERATING', '생성 중'), ('COMPLETED', '생성완료'),
                                      ('FAILED', '생성실패')],
                             default='PENDING',
                             max_length=20,
                             verbose_name='시너지 생성 상태'),
    ),
    migrations.CreateModel(
      name='ReferralOverallOpinion',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('opinion_for_male', models.TextField(blank=True, default='', verbose_name='남자에게 보여줄 의견')),
        ('opinion_for_female', models.TextField(blank=True, default='', verbose_name='여자에게 보여줄 의견')),
        ('generation_status',
         models.CharField(choices=[('PENDING', '초기화됨'), ('GENERATING', '생성 중'), ('COMPLETED', '생성완료'),
                                   ('FAILED', '생성실패')],
                          default='PENDING',
                          max_length=20,
                          verbose_name='생성 상태')),
        ('error_message', models.TextField(blank=True, default='', verbose_name='에러 메시지')),
        ('referral',
         models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                              related_name='overall_opinion',
                              to='matchmakings.referral',
                              verbose_name='추천')),
      ],
      options={
        'verbose_name': 'Referral Overall Opinion',
        'verbose_name_plural': 'Referral Overall Opinions',
        'db_table': 'referral_overall_opinions',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.CreateModel(
      name='ReferralSynergy',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='시너지 제목')),
        ('description', models.TextField(blank=True, default='', verbose_name='시너지 설명')),
        ('generation_status',
         models.CharField(choices=[('PENDING', '초기화됨'), ('GENERATING', '생성 중'), ('COMPLETED', '생성완료'),
                                   ('FAILED', '생성실패')],
                          default='PENDING',
                          max_length=20,
                          verbose_name='생성 상태')),
        ('error_message', models.TextField(blank=True, default='', verbose_name='에러 메시지')),
        ('referral',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='synergies',
                           to='matchmakings.referral',
                           verbose_name='추천')),
      ],
      options={
        'verbose_name': 'Referral Synergy',
        'verbose_name_plural': 'Referral Synergies',
        'db_table': 'referral_synergies',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.DeleteModel(name='PreMatchingCompatibilityTag', ),
  ]
