# Generated by Django 5.2.5 on 2025-11-05 15:53

import django.db.models.deletion
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ('matchmakings', '0004_remove_prematching_compatibility_tags_and_more'),
  ]

  operations = [
    migrations.CreateModel(
      name='ReferralCompatibilityTag',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('compatibility_tag',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='referral_compatibility_tags',
                           to='matchmakings.compatibilitytag',
                           verbose_name='궁합 태그')),
        ('referral',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='referral_compatibility_tags',
                           to='matchmakings.referral',
                           verbose_name='추천')),
      ],
      options={
        'verbose_name': 'Referral Compatibility Tag',
        'verbose_name_plural': 'Referral Compatibility Tags',
        'db_table': 'referral_compatibility_tags',
        'unique_together': {('referral', 'compatibility_tag')},
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
    migrations.AddField(
      model_name='referral',
      name='compatibility_tags',
      field=models.ManyToManyField(related_name='referrals',
                                   through='matchmakings.ReferralCompatibilityTag',
                                   to='matchmakings.compatibilitytag',
                                   verbose_name='궁합 태그'),
    ),
    migrations.CreateModel(
      name='PreparedCompatibilityTag',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('male_d_stem',
         models.CharField(choices=[('갑', '갑'), ('을', '을'), ('병', '병'), ('정', '정'), ('무', '무'), ('기', '기'), ('경', '경'),
                                   ('신', '신'), ('임', '임'), ('계', '계')],
                          max_length=1,
                          verbose_name='남자 일간')),
        ('male_d_branch',
         models.CharField(choices=[('자', '자'), ('축', '축'), ('인', '인'), ('묘', '묘'), ('진', '진'), ('사', '사'), ('오', '오'),
                                   ('미', '미'), ('신', '신'), ('유', '유'), ('술', '술'), ('해', '해')],
                          max_length=1,
                          verbose_name='남자 일지')),
        ('female_d_stem',
         models.CharField(choices=[('갑', '갑'), ('을', '을'), ('병', '병'), ('정', '정'), ('무', '무'), ('기', '기'), ('경', '경'),
                                   ('신', '신'), ('임', '임'), ('계', '계')],
                          max_length=1,
                          verbose_name='여자 일간')),
        ('female_d_branch',
         models.CharField(choices=[('자', '자'), ('축', '축'), ('인', '인'), ('묘', '묘'), ('진', '진'), ('사', '사'), ('오', '오'),
                                   ('미', '미'), ('신', '신'), ('유', '유'), ('술', '술'), ('해', '해')],
                          max_length=1,
                          verbose_name='여자 일지')),
        ('compatibility_tags',
         models.ManyToManyField(blank=True,
                                related_name='prepared_compatibility_tags',
                                to='matchmakings.compatibilitytag',
                                verbose_name='궁합 태그')),
      ],
      options={
        'verbose_name':
        'Prepared Compatibility Tag',
        'verbose_name_plural':
        'Prepared Compatibility Tags',
        'db_table':
        'prepared_compatibility_tags',
        'indexes': [
          models.Index(fields=['male_d_stem', 'male_d_branch', 'female_d_stem', 'female_d_branch'],
                       name='idx_male_female_ilju'),
          models.Index(fields=['female_d_stem', 'female_d_branch'], name='idx_female_ilju')
        ],
        'unique_together': {('male_d_stem', 'male_d_branch', 'female_d_stem', 'female_d_branch')},
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
