# Generated by Django 5.2.5 on 2025-11-18 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

  dependencies = [
    ('matchmakings', '0005_referralcompatibilitytag_referral_compatibility_tags_and_more'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='ReferralLog',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('referred_at', models.DateTimeField(verbose_name='추천 일시')),
        ('referred_algorithm', models.CharField(max_length=255, verbose_name='추천 알고리즘')),
        ('referral',
         models.ForeignKey(blank=True,
                           null=True,
                           on_delete=django.db.models.deletion.SET_NULL,
                           related_name='logs',
                           to='matchmakings.referral',
                           verbose_name='추천')),
        ('referral_user',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='suggested_referral_logs',
                           to=settings.AUTH_USER_MODEL,
                           verbose_name='추천된 사용자')),
        ('user',
         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                           related_name='received_referral_logs',
                           to=settings.AUTH_USER_MODEL,
                           verbose_name='추천을 받은 사용자')),
      ],
      options={
        'verbose_name': 'Referral Log',
        'verbose_name_plural': 'Referral Logs',
        'db_table': 'referral_logs',
      },
      managers=[
        ('objects', common.models.base_model.BaseModelManager()),
      ],
    ),
  ]
