# Generated by Django 5.2.5 on 2025-11-18 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('matchmakings', '0006_referrallog'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddConstraint(
      model_name='referral',
      constraint=models.UniqueConstraint(fields=('user', 'referral_user'), name='unique_user_referral_user'),
    ),
  ]
