# Generated by Django 5.2.5 on 2025-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('matchmakings', '0007_referral_unique_user_referral_user'),
  ]

  operations = [
    migrations.AddField(
      model_name='referralconversation',
      name='opposite_conversation_messages',
      field=models.JSONField(default=list,
                             help_text='ConversationMessage 형태의 대화 메시지 리스트',
                             verbose_name='호감을 받는 사람에게 노출할 대화 메시지'),
    ),
  ]
