# Generated by Django 5.2.7 on 2025-11-02 06:28

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import games.models.game
import games.models.game_result
import games.models.game_session


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_child"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[("BB_STAR", "아기별 게임"), ("KIDS_TRAFFIC", "키즈 교통 게임")],
                        help_text="게임 고유 코드 (BB_STAR, KIDS_TRAFFIC 등)",
                        max_length=32,
                        unique=True,
                        verbose_name="게임 코드",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="표시명")),
                ("is_active", models.BooleanField(default=True, verbose_name="사용 여부")),
            ],
            options={
                "verbose_name": "게임",
                "verbose_name_plural": "게임",
                "db_table": "games",
                "constraints": [models.UniqueConstraint(fields=("code",), name="unique_game_code")],
            },
            managers=[
                ("objects", games.models.game.GameManager()),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="세션 ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "시작"),
                            ("COMPLETED", "완료"),
                            ("GAME_OVER", "게임 오버"),
                            ("FORFEIT", "포기"),
                        ],
                        default="STARTED",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                ("round_current", models.SmallIntegerField(default=1, verbose_name="현재 라운드")),
                ("score_current", models.IntegerField(default=0, verbose_name="진행 중 누계 점수")),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="라운드 진행상태 등 임시 값",
                        null=True,
                        verbose_name="메타데이터",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="시작 시각")),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="종료 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="users.child",
                        verbose_name="아동",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="games.game",
                        verbose_name="게임",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="부모",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 세션",
                "verbose_name_plural": "게임 세션",
                "db_table": "game_sessions",
                "ordering": ["-started_at"],
            },
            managers=[
                ("objects", games.models.game_session.GameSessionManager()),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField(verbose_name="총점")),
                ("wrong_count", models.IntegerField(blank=True, default=0, null=True, verbose_name="오답 수")),
                (
                    "reaction_ms_avg",
                    models.IntegerField(
                        blank=True, help_text="평균 반응 시간 (밀리초)", null=True, verbose_name="평균 반응(ms)"
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="성공률 (0.00 ~ 100.00)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="성공률(%)",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, help_text="라운드별 상세 데이터", null=True, verbose_name="메타데이터"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="기록 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results",
                        to="users.child",
                        verbose_name="아동",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results",
                        to="games.game",
                        verbose_name="게임",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="games.gamesession",
                        verbose_name="게임 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 결과",
                "verbose_name_plural": "게임 결과",
                "db_table": "game_results",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("session",), name="unique_session_result")],
            },
            managers=[
                ("objects", games.models.game_result.GameResultManager()),
            ],
        ),
    ]
