# Generated by Django 5.2.7 on 2025-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesession",
            old_name="round_current",
            new_name="current_round",
        ),
        migrations.RenameField(
            model_name="gamesession",
            old_name="score_current",
            new_name="current_score",
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="reaction_ms_avg",
            field=models.IntegerField(blank=True, help_text="평균 반응 시간", null=True, verbose_name="평균 반응(ms)"),
        ),
    ]
