# Generated by Django 5.2.7 on 2025-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_rename_round_current_gamesession_current_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gameresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
