# Generated by Django 5.2.7 on 2025-11-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_gameresult_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameresult",
            name="reaction_ms_avg",
        ),
        migrations.RemoveField(
            model_name="gameresult",
            name="success_rate",
        ),
        migrations.AddField(
            model_name="gameresult",
            name="reaction_ms_sum",
            field=models.IntegerField(
                blank=True, help_text="모든 반응 시간의 합계", null=True, verbose_name="반응 시간 합계(ms)"
            ),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="round_count",
            field=models.IntegerField(blank=True, help_text="완료한 라운드 수", null=True, verbose_name="라운드 수"),
        ),
        migrations.AddField(
            model_name="gameresult",
            name="success_count",
            field=models.IntegerField(blank=True, help_text="성공한 횟수", null=True, verbose_name="성공 횟수"),
        ),
    ]
