# Generated by Django 5.2.7 on 2025-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_remove_gameresult_reaction_ms_avg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="max_round",
            field=models.IntegerField(
                default=10, help_text="게임의 최대 라운드 수 (기본값: 10)", verbose_name="최대 라운드"
            ),
        ),
    ]
