# Generated by Django 5.2.7 on 2025-11-11 09:08

import django.db.models.deletion
import games.models.ranking_entry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_max_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(help_text='데모부스에서 입력한 참가자 이름', max_length=100, verbose_name='참가자 이름')),
                ('score', models.IntegerField(help_text='게임 점수', verbose_name='점수')),
                ('round_count', models.IntegerField(blank=True, help_text='도달한 최종 라운드 수', null=True, verbose_name='도달한 라운드')),
                ('contact_info', models.CharField(blank=True, help_text='참가자 연락처 (선택)', max_length=200, null=True, verbose_name='연락처')),
                ('is_event_highlighted', models.BooleanField(default=False, help_text='최고점 갱신 시 이벤트 표시 여부', verbose_name='이벤트 하이라이트')),
                ('event_triggered_at', models.DateTimeField(blank=True, help_text='최고점 갱신 이벤트가 발생한 시각', null=True, verbose_name='이벤트 발생 시각')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to='games.game', verbose_name='게임')),
                ('game_result', models.ForeignKey(blank=True, help_text='연결된 게임 결과 (선택적)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_entry', to='games.gameresult', verbose_name='게임 결과')),
            ],
            options={
                'verbose_name': '랭킹 엔트리',
                'verbose_name_plural': '랭킹 엔트리',
                'db_table': 'ranking_entries',
                'ordering': ['-score', '-round_count', 'created_at'],
                'indexes': [models.Index(fields=['game', '-score'], name='ranking_ent_game_id_513521_idx')],
            },
            managers=[
                ('objects', games.models.ranking_entry.RankingEntryManager()),
            ],
        ),
    ]
