# Generated by Django 5.2.7 on 2025-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_rankingentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingentry",
            name="organization",
            field=models.CharField(
                blank=True, help_text="참가자 소속 (학교, 회사 등)", max_length=30, null=True, verbose_name="소속"
            ),
        ),
    ]
