# Generated by Django 5.1.5 on 2025-03-16 07:46

import config.models.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="bookmark title"),
                ),
                (
                    "bookmarkings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="bookmarkings count"
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmark",
                "verbose_name_plural": "bookmarks",
                "db_table": "bookmarks",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bookmarking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bookmarking",
                "verbose_name_plural": "bookmarkings",
                "db_table": "bookmarkings",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
