# Generated by Django 5.1.5 on 2025-03-16 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookmark", "0001_initial"),
        ("meme", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="bookmarking",
            name="bookmark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarkings",
                to="bookmark.bookmark",
                verbose_name="bookmark",
            ),
        ),
        migrations.AddField(
            model_name="bookmarking",
            name="meme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarkings",
                to="meme.meme",
                verbose_name="meme",
            ),
        ),
        migrations.AddField(
            model_name="bookmarking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarkings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarking",
            index=models.Index(
                fields=["meme", "bookmark"], name="bookmarking_meme_id_4baa0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarking",
            constraint=models.UniqueConstraint(
                fields=("meme", "bookmark"), name="unique_meme_bookmark"
            ),
        ),
    ]
