# Generated by Django 5.1.7 on 2025-08-20 06:58

import bookmark.models.bookmarking
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0002_initial"),
        ("meme", "0007_memo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookmarking",
            managers=[
                ("objects", bookmark.models.bookmarking.BookmarkingModelManager()),
            ],
        ),
        migrations.AlterField(
            model_name="bookmarking",
            name="bookmark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarkings",
                to="bookmark.bookmark",
                verbose_name="bookmark",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarking",
            constraint=models.UniqueConstraint(
                fields=("user", "meme", "bookmark"), name="unique_user_meme_bookmark"
            ),
        ),
    ]
