# Generated by Django 5.1.7 on 2025-08-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0003_alter_bookmarking_managers_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmarking",
            name="unique_meme_bookmark",
        ),
    ]
