# Generated by Django 5.2.7 on 2025-11-02 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportPin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pin_hash", models.CharField(max_length=256, verbose_name="Pin Hash")),
                ("enabled_at", models.DateTimeField(blank=True, null=True, verbose_name="Enabled At")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_pin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Pin",
                "verbose_name_plural": "Report Pins",
                "db_table": "report_pins",
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
    ]
