# Generated by Django 5.2.7 on 2025-11-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reports.models.game_report
import reports.models.game_report_advice
import reports.models.report


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_remove_gameresult_reaction_ms_avg_and_more"),
        ("reports", "0001_initial"),
        ("users", "0003_child"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="게임 결과를 추합한 게임과 관련된 추가 메타 정보",
                        null=True,
                        verbose_name="메타 정보",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_reports",
                        to="games.game",
                        verbose_name="게임",
                    ),
                ),
                (
                    "last_reflected_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="가장 최근 반영된 게임 세션",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reflected_in_game_reports",
                        to="games.gamesession",
                        verbose_name="마지막 반영 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 레포트",
                "verbose_name_plural": "게임 레포트",
                "db_table": "game_reports",
                "ordering": ["-updated_at"],
            },
            managers=[
                ("objects", reports.models.game_report.GameReportManager()),
            ],
        ),
        migrations.CreateModel(
            name="GameReportAdvice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="조언 제목", max_length=255, verbose_name="제목")),
                ("description", models.TextField(help_text="조언 상세 내용", verbose_name="설명")),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="조언 생성 중 발생한 오류 메시지", null=True, verbose_name="오류 메시지"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_advices",
                        to="games.game",
                        verbose_name="게임",
                    ),
                ),
                (
                    "game_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advices",
                        to="reports.gamereport",
                        verbose_name="게임 레포트",
                    ),
                ),
            ],
            options={
                "verbose_name": "게임 레포트 조언",
                "verbose_name_plural": "게임 레포트 조언",
                "db_table": "game_report_advices",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", reports.models.game_report_advice.GameReportAdviceManager()),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concentration_score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="아동의 집중력 점수 (0-100)", verbose_name="집중력 점수"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_games_played", "게임 미플레이"),
                            ("no_up_to_date", "최신 아님"),
                            ("pending", "대기 중"),
                            ("generating", "진행 중"),
                            ("completed", "완료"),
                            ("error", "오류 발생"),
                        ],
                        default="no_games_played",
                        help_text="레포트의 현재 상태",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="users.child",
                        verbose_name="아동",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "레포트",
                "verbose_name_plural": "레포트",
                "db_table": "reports",
                "ordering": ["-updated_at"],
            },
            managers=[
                ("objects", reports.models.report.ReportManager()),
            ],
        ),
        migrations.AddField(
            model_name="gamereport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_reports",
                to="reports.report",
                verbose_name="레포트",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(fields=("user", "child"), name="unique_user_child_report"),
        ),
        migrations.AddConstraint(
            model_name="gamereport",
            constraint=models.UniqueConstraint(fields=("report", "game"), name="unique_report_game"),
        ),
    ]
