# Generated by Django 5.2.7 on 2025-11-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_gamereport_gamereportadvice_report_gamereport_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("no_games_played", "게임 미플레이"),
                    ("pending", "대기 중"),
                    ("generating", "진행 중"),
                    ("completed", "완료"),
                    ("error", "오류 발생"),
                ],
                default="no_games_played",
                help_text="레포트의 현재 상태",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
