# Generated by Django 5.2.7 on 2025-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_report_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamereport",
            name="max_rounds_count",
            field=models.IntegerField(
                default=0,
                help_text="game의 max_round와 round_count가 같은 경우의 수",
                verbose_name="최대 도달 라운드 횟수",
            ),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_play_actions_count",
            field=models.IntegerField(
                default=0, help_text="success_count + wrong_count", verbose_name="전체 플레이 액션 수"
            ),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_play_rounds_count",
            field=models.IntegerField(
                default=0, help_text="GameResult의 round_count 합", verbose_name="전체 플레이 라운드 수"
            ),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_plays_count",
            field=models.IntegerField(default=0, help_text="GameResult의 개수", verbose_name="전체 플레이 횟수"),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_reaction_ms_sum",
            field=models.BigIntegerField(
                default=0, help_text="reaction_ms_sum 누적값 (밀리초)", verbose_name="총 반응시간 합계"
            ),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_success_count",
            field=models.IntegerField(default=0, help_text="success_count 누적", verbose_name="전체 성공 횟수"),
        ),
        migrations.AddField(
            model_name="gamereport",
            name="total_wrong_count",
            field=models.IntegerField(default=0, help_text="wrong_count 누적", verbose_name="전체 오답 횟수"),
        ),
    ]
